day_14/src/glassdoor/glassdoor/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ninja/', include('ninjas.urls')),
]

day_14/src/glassdoor/ninjas/urls.py
from django.urls import path

from . import views
app_name = "ninjas"
urlpatterns = [
    path('', views.IndexList.as_view(), name='index'),
    path('<int:dev_id>/', views.DetailsList.as_view(), name='details'),
    path('<str:skill>/', views.DevelopersList.as_view(), name='developers'),
    path('<int:dev_id>/level/', views.level, name='level'),
]

day_14/src/glassdoor/ninjas/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Developer(models.Model):
    name = models.CharField(max_length = 40)
    experience = models.FloatField()
    country = models.CharField(max_length = 30)

    def __repr__(self):
        return self.name

class Skill(models.Model):
    name = models.CharField(max_length = 50)
    level = models.IntegerField()
    developer = models.ForeignKey(Developer, on_delete =  models.CASCADE)

    def __repr__(self):
        return self.name + " " + self.level
    def get_absolute_url(self):
        return reverse('ninjas:details',args=(self.developer,))

day_14/src/glassdoor/ninjas/views.py
from django.shortcuts import get_object_or_404

# Create your views here.
from .models import Developer
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView

#class-based generic views

class IndexList(ListView):
    template_name = 'ninja/index.html'
    context_object_name = 'devs'

    def get_queryset(self):
        return Developer.objects.all()
    
class DetailsList(ListView):
    model = Developer
    template_name = 'ninja/details.html'
    context_object_name = 'dev'
    def get_queryset(self):
        return Developer.objects.filter(pk=self.kwargs['dev_id']).first()

class DevelopersList(ListView):
    model = Developer
    template_name = 'ninja/developers.html'
    context_object_name = 'devs'   
    def get_queryset(self):
        return Developer.objects.filter(skill__name=self.kwargs['skill'])
    
#Function-Based Views

def level(request, dev_id):
    dev = get_object_or_404(Developer, pk=dev_id)
    select = dev.skill_set.get(pk=request.POST['skill'])
    select.level += 1
    select.save()
    return HttpResponseRedirect(reverse('ninjas:details',args=(dev_id,)))

day_14/src/glassdoor/ninjas/templates/ninja/details.html
<h1>{{dev.name}}</h1>
<form action="{% url 'ninjas:level' dev.id %}" method="post">
{% csrf_token %}
<table>
    <tr><th>Name</th>
    <th>Level</th>
    <th>UpGrade</th></tr>
    {% for lang in dev.skill_set.all %}
        <tr>
            <td>{{lang.name}}</td>
            <td>{{lang.level}}</td>
            <td><input type="radio" name="skill" id="skill{{forloop.counter}}" value="{{lang.id}}"></td>
        </tr>
    {% endfor %}
</table>
<input type="submit" value="Level Up">
</form>

day_14/src/glassdoor/ninjas/templates/ninja/developers.html
{% if devs %}
    <table>
        <tr>
            <th>Name</th>
            <th>Experience</th>
            <th>Country</th>
        </tr>

        {% for dev in devs %}
        <tr>
            <td><a href="{% url 'ninjas:details' dev.id %}">{{dev.name}}</a></td>
            <td>{{dev.experience}}</td>
            <td>{{dev.country}}</td>
        </tr>
        {% endfor %}

    </table>
{% else %}
    <h1>No Data in Developers</h1>
{% endif %}

day_14/src/glassdoor/ninjas/templates/ninja/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'ninjas/style.css' %}">
{% if devs %}
    <table>
        <tr>
            <th>Name</th>
            <th>Experience</th>
            <th>Country</th>
        </tr>

        {% for dev in devs %}
        <tr>
            <td><a href="{% url 'ninjas:details' dev.id %}">{{dev.name}}</a></td>
            <td>{{dev.experience}}</td>
            <td>{{dev.country}}</td>
        </tr>
        {% endfor %}

    </table>
{% else %}
    <h1>No Data in Developers</h1>
{% endif %}