day_12/src/glassdoor/ninjas/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:dev_id>/', views.details, name='details'),
    path('<str:skill>/', views.developers, name='developers'),
]

day_12/src/glassdoor/ninjas/models.py
from django.db import models

# Create your models here.
class Developer(models.Model):
    name = models.CharField(max_length = 40)
    experience = models.FloatField()
    country = models.CharField(max_length = 30)

    def __repr__(self):
        return self.name

class Skill(models.Model):
    name = models.CharField(max_length = 50)
    level = models.CharField(max_length = 50)
    developer = models.ForeignKey(Developer, on_delete =  models.CASCADE)

    def __repr__(self):
        return self.name + " " + self.level

day_12/src/glassdoor/ninjas/views.py
from django.shortcuts import render,get_object_or_404

# Create your views here.
from .models import Developer,Skill

def index(request):
    devs = Developer.objects.all()
    context = {
        'devs' : devs
    }
    return render(request, 'ninja/index.html', context)

def details(request, dev_id):
    dev = get_object_or_404(Developer, pk=dev_id)
    return render(request, 'ninja/details.html', {'dev':dev})

def developers(request,skill):
    devs = Developer.objects.filter(skill__name=skill)
    context = {
        'devs' : devs
    }
    return render(request, 'ninja/developers.html', context)

day_12/src/glassdoor/templates/ninja/details.html
<h2>{{dev.name}}</h2>
<table>
    <tr><th>Skill</th>
    <th>Level</th></tr>
    {% for lang in dev.skill_set.all %}
        <tr>
            <td>{{lang.name}}</td>
            <td>{{lang.level}}</td>
        </tr>
    {% endfor %}
</table>

day_12/src/glassdoor/templates/ninja/developers.html
{% if devs %}
    <table>
        <tr>
            <th>Name</th>
            <th>Experience</th>
            <th>Country</th>
        </tr>

        {% for dev in devs %}
        <tr>
            <td><a href="{% url 'details' dev.id %}">{{dev.name}}</a></td>
            <td>{{dev.experience}}</td>
            <td>{{dev.country}}</td>
        </tr>
        {% endfor %}

    </table>
{% else %}
    <h1>No Data in Developers</h1>
{% endif %}

day_12/src/glassdoor/templates/ninja/index.html
{% if devs %}
    <table>
        <tr>
            <th>Name</th>
            <th>Experience</th>
            <th>Country</th>
        </tr>

        {% for dev in devs %}
        <tr>
            <td><a href="{% url 'details' dev.id %}">{{dev.name}}</a></td>
            <td>{{dev.experience}}</td>
            <td>{{dev.country}}</td>
        </tr>
        {% endfor %}

    </table>
{% else %}
    <h1>No Data in Developers</h1>
{% endif %}